name: "Remove a folder from a specific repository"
description: "Remove a folder from a specific repository"
author: "Avinash Kumar"
inputs:  
  organization:
    description: "Organization name of the repository"
    required: true
  repo_name:
    description: "Name of the repository"
    required: true
  pat:
    description: "pat token"
    required: true
  folder_name:
    description: "folder Name of the repository"
    required: true
runs:
  using: "composite"
  steps:
    - name: 'Check out repository'
      uses: actions/checkout@v4
    - name: folder delete 
      id: folder_delete
      shell: pwsh
      run: |
        $repo_name = "${{ inputs.repo_name }}"
        $organization = "${{ inputs.organization }}"
        $pat = "${{ inputs.pat }}"
        $folder_name = "${{ inputs.folder_name }}"
        
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git config --global init.defaultBranch main
        git init
        git clone "https://bogususer:${{inputs.pat}}@github.com/$organization/$repo_name.git"
        ls ./$repo_name
        cd ./$folder_name
        Get-ChildItem -Path "./" -Recurse | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue

        # git rm -r --cached $folder_name
        git add .
        git commit -m "Removed folder from repository"
        git push origin main
        # $repodeleteuri = "https://api.github.com/repos/$organization/$repo_name/contents/$folder_name"
        # Invoke-RestMethod -Uri $repodeleteuri -Method Delete -Headers @{Authorization = "token $pat"}

